#!/bin/sh
echo " "
rm -rf /usr/share/enigma2/Nacht
rm -rf /usr/lib/enigma2/python/Components/Converter/Nacht*
rm -rf /usr/lib/enigma2/python/Components/Renderer/Nacht*
rm -rf /usr/lib/enigma2/python/Tools/Nacht*
echo " "
echo " " 
echo "********************************************"	 
echo " "														 
echo "	skin successfully removed...  "
echo " "	
echo "********************************************"	 
echo " "  
exit 0												 
